name: Post Release

on:
  push:
    branches:
      - feat/add-post-release-workflow
    tags:
      - "*@*.*.*"
  workflow_dispatch:

jobs:
  extract-project:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Project Name
        id: extract
        run: |
          TAG_NAME=${{ github.ref_name }}
          PROJECT_NAME=$(echo "$TAG_NAME" | sed -E 's/@[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?//')
          echo "project=$PROJECT_NAME" >> "$GITHUB_ENV"
          echo "::set-output name=project::$PROJECT_NAME"

      - name: Show Extracted Project
        run: |
          echo "Extracted project: ${{ env.project }}"

  use-project:
    runs-on: ubuntu-latest
    needs: extract-project
    steps:
      - name: Use Extracted Project Name
        run: echo "Project from tag is ${{ needs.extract-project.outputs.project }}"
